### ISSUE TITLE
Requesting 'Data Query' tab label name be set to 'Data connection' label name

### ISSUE THREAD

**Issue by angrybirdnut** [jumpinjackie/fdotoolbox#20]
When importing a feature data set (e.g. SDF file) , there is an option to name the connection to that data set. However, when you perform a Data Query of that data-set, the name you provided does not appear in the tab header for the results of the query. Instead, the same generic name "Data Query" appears in all tabs/queries. It is this difficult to know which tab belongs to which connection (especially if you do not click to run each query in sequential order). I am requesting that the connection name be carried along to the tab name of the Data Query. Please see attached screenshot for a depiction of this.
I am using the (excellent) FDO Toolbox - version 1.3.0.0
![fdo_toolbox_featurerequest](https://user-images.githubusercontent.com/8793109/41113734-6a70c90c-6a50-11e8-8204-db2cf4d9c058.png)

**Comment by jumpinjackie** [comment]
Good idea!
