### ISSUE TITLE
Installer FDOToolBox 1.3 

### ISSUE THREAD

**Issue by begu24** [jumpinjackie/fdotoolbox#7]
The installer of FDOToolBox 1.3 stops with a message that the .NET Framework 2.0 is required even though the code has been updated to use .NET Framework 4.5. Can't proceed with installation without installing .NET Framework 2.0.

**Comment by jumpinjackie** [comment]
Fixed as part of installer changes to target .net Frameowrk 4.8 / vcredist 2015 for 1.4
