### ISSUE TITLE
Connection to GPKG SQLite

### ISSUE THREAD

**Issue by cityofhollywoodgeospatial** [jumpinjackie/fdotoolbox#73]
How do you setup a Connection to GPKG
it seems to expect SQLite to be .sqlite or .db and does not allow connecting to OGC GPKG

**Comment by jumpinjackie** [comment]
The GDAL/OGR that comes with FDO (that we use) is built with the default driver set (ie. Anything on [this list](https://gdal.org/drivers/vector/index.html) where **Build Requirements** are `Built-in by default`). 

This does not include SQLite or any SQLite-based format (like GPKG) by default so you will not get support for connecting to such data sources by default.

What we normally do in this case (same thing we do with downstream client FDO applications like MapGuide), is to source an alternative binary build of the same version of GDAL/OGR (built with the same MSVC 2015 compiler) which has support for these drivers built in.

In our case, you want to grab the GDAL 2.2.3 binaries from gisinternals [here](https://www.gisinternals.com/query.html?content=filelist&file=release-1900-x64-gdal-2-2-3-mapserver-7-0-7.zip): 

Extract the contents of the `bin` folder from this zip file into the `FDO` directory of your FDO Toolbox installation, overwriting all existing dll files.

Then start FDO Toolbox and you can connect to your gpkg files using the OGR connect dialog.

If you want to be lazy and be able to just drag and drop connect to such files in the future, you can edit `FileExtensionMappings.xml` and add this entry for `.gpkg` files:

```
    <FileExtension>
        <Name>gpkg</Name>
        <Description>GeoPackage files</Description>
        <Provider>OSGeo.OGR</Provider>
        <ConnectionString>DataSource={{__FILE__}};DefaultSchemaName=Default</ConnectionString>
    </FileExtension>
```

This will allow you to drag and drop gpkg files into FDO Toolbox to connect to them.

Hope that helps.
