### ISSUE TITLE
FdoCmd list-connection-params command problems

### ISSUE THREAD

**Issue by ziemiowid** [jumpinjackie/fdotoolbox#77]
FdoCmd command list-connection-params has a flaw which make its use limited. I expected that this command should accept single option: `--provider`, but it is not working that way.

This command has unexpected help screen:

```plaintext
$> fdocmd list-connection-params --help
FdoCmd 1.5.1.180
Copyright � Jackie Ng 2008-2020
USAGE:
List SQL Server Connection Parameters:
  FdoCmd list-class-properties --class MyFeatureClass --connect-params Service
  mysqlserverhostnameorip Username myusername Password mypassword DataStore
  MyDatabase --provider OSGeo.SQLServerSpatial --schema Default

  --full-details      (Default: false) If specified, print out full details of
                      each parameter

  --provider          Required. The FDO provider name

  --connect-params    Required. Connection Parameters. Must be in the form of:
                      <name1> <value1> ... <nameN> <valueN>

  --from-file         Required. The path to the data file to create a FDO
                      connection from

  --help              Display this help screen.

  --version           Display version information.

```

Header of USAGE section suggests that it's about listing of connection parameters, but provided example is taken from `list-class-properties` command. Maybe description of command parameters is also for `list-class-properties`.

It is possible to get connection parameters for some drivers using `--from-file` option. I suppose that it's possible for SDF, SQLite and SHP data.

Unfortunately, when I tried to get listing of connection parameters with `--provider` option, I got rather unexpected `Required option 'connect-params' is missing.` message.

Do I have to know connection parameters for given provider to learn what parameters this provider uses?

```plaintext
$> fdocmd list-connection-params --provider OSGeo.SDF.4.1
FdoCmd 1.5.1.180
Copyright � Jackie Ng 2008-2020

ERROR(S):
  Required option 'connect-params' is missing.
USAGE:
List SQL Server Connection Parameters:
  FdoCmd list-class-properties --class MyFeatureClass --connect-params Service
[...]
```

**Comment by jumpinjackie** [comment]
I will put out a 1.5.2 release shortly that will make `--connect-params` optional if `--provider` is specified
