### ISSUE TITLE
"A Data Property cannot have a negative precision" while using fdocmd.exe create-file on non negative precision decimal

### ISSUE THREAD

**Issue by bertvanovermeir** [jumpinjackie/fdotoolbox#84]
It seems there might be a bug (or I am doing it wrong) when trying to create a new file with a new schema that contains a restriction base xs:decimal:

> <xs:element name="theoretischeLevensduur" minOccurs="0" default="" nillable="true">
            <xs:annotation>
              <xs:documentation>De levensduur in aantal maanden die theoretisch mag verwacht worden voor een object.</xs:documentation>
            </xs:annotation>
            <xs:simpleType>
              <xs:restriction base="xs:decimal">
              </xs:restriction>
            </xs:simpleType>
          </xs:element>

with or without a restriction:

> <xs:totalDigits value="19" />
                <xs:fractionDigits value="10" />

After running this command:

`fdocmd create-file --file <path> --schema-path <path>`

The following error is displayed:

`OSGeo.FDO.Common.Exception: A Data Property cannot have a negative precision.
   at OSGeo.FDO.Schema.DataPropertyDefinition.set_Precision(Int32 value)`

Which results in the file still being created, but further feature copy actions will fail with the same error.

Thanks in advance.
[schema.txt](https://github.com/jumpinjackie/fdotoolbox/files/11380769/schema.txt)

**Comment by jumpinjackie** [comment]
Thanks for the useful report. Can you tell me what kind of file you were trying to create (`.sdf`, `.shp`, other?) ?

**Comment by bertvanovermeir** [comment]
Thank you for replying.

I am using `.sdf` files and the latest version at the time of writing `(1.5.2.190)`.

**Comment by jumpinjackie** [comment]
Fix will be in the upcoming 1.5.3 release
